container:
  image: cirrusci/flutter:latest
  cpu: 4
  memory: 10G

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test
  
check_android_task:
  create_device_script: >
    echo no | avdmanager create avd --force \
        -n test \
        -k "system-images;android-18;default;armeabi-v7a"
  start_emulator_background_script: >
    $ANDROID_HOME/emulator/emulator \
        -avd test \
        -no-audio \
        -no-window
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test
  wait_for_emulator_script:
    - adb wait-for-device
    - adb shell input keyevent 82
  integration_test_script: flutter drive --target=test_driver/app.dart
