container:
  image: cirrusci/flutter:latest
  cpu: 4
  memory: 16G

flutter_task:
  install_sdk_cache:
    folder: $ANDROID_HOME/system-images
    populate_script: sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
  create_device_script: >
    echo no | avdmanager create avd --force \
        -n test \
        -k "system-images;android-25;google_apis;armeabi-v7a"
  start_emulator_background_script: >
    $ANDROID_HOME/emulator/emulator \
        -avd test \
        -no-audio \
        -no-window
  widget_tests_script: flutter test --coverage
  wait_for_emulator_script:
    - adb wait-for-device
  integration_tests_script: flutter drive --target=test_driver/app.dart
